### ISSUE TITLE
offsprint_file format

### ISSUE THREAD

**Issue by wsuplantpathology** [johnomics/scripts#1]
Hi:

I was trying to use your script convert_vcf_to_joinmap.pl. I wonder what is offspirng file? Could you please describe or give an example format for this file? Thanks in advance.

Best,
Chongjing

**Comment by johnomics** [comment]
Hi Chongjing,

I would not recommend using this script today. It was written in 2011 and I haven’t used it for a long time. I suspect it will not parse new VCFs correctly.  

If you want to try it, the offspring file should contain lines like this, with sample names and sexes separated by whitespace:  
Mother F  
Father M  
Offspring1 F  
Offspring2 F  

The sexes can be specified with anything (F,M,Female,Male,fem,m etc etc) as long as the string starts with F,f,M or m.  

The names can also be anything you like (they don’t need to be Mother, Father etc). Although it’s called the offspring file, the parents should be included in this file, and then the parental names specified on the command line, e.g.  

convert_vcf_to_joinmap.pl -o offspring.tsv -m Mother -f Father  

if your parent names are Mother and Father.

**Comment by wsuplantpathology** [comment]
Hi johnomics:

Thanks so much for your response. I cannot find more recent of such a script. I followed your suggestions, but seems got another issue:
here is my command: `convert_vcf_to_joinmap.pl --vcf 3.29.filter.recode.vcf --offspring offsprings.txt --mother Parent2 --father Parent1 --prefix test`

I got error like this: `Illegal division by zero at /data/chen/software/convert_vcf_to_joinmap.pl line 232, <$vcf_file> line 522.`

Could you please help me to figure out this again?
 I attach my .vcf and offsprings.txt. 
[offsprings.txt](https://github.com/johnomics/scripts/files/1612341/offsprings.txt)
[3.29.filter.recode.txt](https://github.com/johnomics/scripts/files/1612376/3.29.filter.recode.txt)


Thanks so much.

Best,
Chongjing

**Comment by johnomics** [comment]
The problem is you have no males in your cross, which the script did not expect. I have fixed the script to allow this. Please try again with the new version.

**Comment by wsuplantpathology** [comment]
Hi johnomics:

Thanks so much for your revised script. It worked, and I got some results. However, I still have a question. After I ran this: `/data/chen/software/convert_vcf_to_joinmap.pl --vcf 3.29.filter.recode.vcf --offspring offsprings.txt --mother Parent2 --father Parent1 --prefix test`,  I only got 390 marker left in test.patterns. Totally I have around 3000 markers in .vcf, and most of them have very good quality. I wonder why only few of the raw variations in .vcf left in .patterns file ?

I do find that if I use lower -q quality_threshold, e.g. 1, I'll get more marker left, but still only get 542 marker, much less than raw markers in .vcf file. So how did the script filter the markers? sorry I don't understand too much about perl, but your script is very useful. Thanks again.

Best,
Chongjing

**Comment by johnomics** [comment]
Most of your SNPs have identical genotypes for both parents, so there is no information to generate a marker from.

**Comment by wsuplantpathology** [comment]
Thanks so much for your explanation. In fact, my population is from selfing. I arbitrarily duplicated the parental sample to create Parent1 and Parent2. Meaning, the Parent1 and Parent2 are identical. Is there a way to deal with this situation? 
  My thinking is, my population can be consider as a CP population, in which hkxhk will be segregation type. In genetic mapping, I'll only use the markers with 1:2:1 ratio. Sounds reasonable?

Many thanks.

**Comment by johnomics** [comment]
Unfortunately, I don't think it's possible to use only hkxhk markers from a pure self cross. To build a linkage map, you need to be able to identify which alleles came from the mother and which from the father. I don't think that's possible when both parents are absolutely identical, but maybe there's a method I don't know about. By all means try running the markers through JoinMap, but you really need a backcross or maybe an F2 cross for linkage mapping.

**Comment by wsuplantpathology** [comment]
Thanks again. This is a fungus, it's hard to get backcross or F2 cross. I read from JoinMap manual that the CP population does not require phase information since JoinMap can estimate this information. My another thinking is probably I can try to use haplotype phasing method to build haplotypes. Anyway, building a genetic map is hard for our fungus.

I think my original questions for you is that, is there a way to convert all SNPs from my original vcf file without any quality filtering? because the SNPs in vcf file have been already filtered using vcftools, so I want to keep all the SNPs during format converting. Thanks

**Comment by johnomics** [comment]
Please try the new version. The script was written for scaffolding genome assemblies, and so rejected any markers that only occurred once, or only occurred on one scaffold. I have now changed the default behaviour so that all markers passing the quality threshold -q are output, and added an option -r to restore the original behaviour to reject singletons.

On your test data set, with -q 0, I now get 1075 patterns output by default, and 541 with -r as you did before (ignoring the header line). 1075 patterns is the most that can be output, because this is all the SNPs where the parents are heterozygous - the rest are homozygous or missing. Hope this helps.

**Comment by wsuplantpathology** [comment]
Hi johnomics:

Thanks very much for all your kind help, I appreciate. This new version works great, and I got what I want. It is very helpful. 

Best,
Chongjing

**Comment by johnomics** [comment]
Great, glad it worked! Best wishes, John
